<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= isset($payload['title']) ? $payload['title'] : 'Ошибка' ?></title>
    <link rel="stylesheet" href="/app/assets/css/style.css">
</head>

<body>
    <header class="header">
        <nav>
            <?php if (isset($payload['menu'])): ?>
                <?php foreach ($payload['menu'] as $item): ?>
                    <a href="<?= $item['link'] ?>"><?= $item['title'] ?></a>
                <?php endforeach; ?>
            <?php endif; ?>
        </nav>
    </header>

    <main class="main">
        <?php include_once VIEW . $content_view ?>
    </main>

    <footer class="footer">
        <span>&copy;&nbsp;Darya-pro, 2024</span>
    </footer>

</body>

</html>